//
//  HomeViewController.swift
//  TestiOS
//
//  Created by javier apaez on 29/07/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import FirebaseDatabase

protocol HomeDisplayLogic: AnyObject {
    func displaySomething(viewModel: Home.Charts.ViewModel)
    func displayNewBackgroundColor(viewModel: Home.BackgroundColor.ViewModel)
}

class HomeViewController: UIViewController, HomeDisplayLogic {
    var interactor: HomeBusinessLogic?
    var router: (NSObjectProtocol & HomeRoutingLogic & HomeDataPassing)?
    let homeView = HomeView()
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: - Setup Clean Code Design Pattern
    
    private func setup() {
        let viewController = self
        let interactor = HomeInteractor()
        let presenter = HomePresenter()
        let router = HomeRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: - Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: - View lifecycle
    override func loadView() {
        view = homeView
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        title = "Home"
        
        homeView.tableView.delegate = self
        homeView.tableView.dataSource = self
        homeView.delegate = self
        
        let request = Home.Charts.Request()
        interactor?.addDatabaseObserver(request: request)
       
    }
    
    // MARK: - request data from HomeInteractor
    func showCharts() {
        let request = Home.Charts.Request()
        interactor?.showCharts(request: request)
    }
    
    // MARK: - display view model from HomePresenter
    
    func displaySomething(viewModel: Home.Charts.ViewModel) {
        router?.routeToCharts()
    }
    
    func displayNewBackgroundColor(viewModel: Home.BackgroundColor.ViewModel) {
        self.homeView.backgroundColor = UIColor(hexString: "#\(viewModel.hexColor)")
    }
}


