//
//  HomeModels.swift
//  TestiOS
//
//  Created by javier apaez on 29/07/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home{
    // MARK: Use cases
    
    enum Charts {
        struct Request {
            
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
    
    enum BackgroundColor {
        struct Request {
            
        }
        
        struct Response {
            let hexColor: String
        }
        
        struct ViewModel {
            let hexColor: String
        }
    }
}
