//
//  HomePresenter.swift
//  TestiOS
//
//  Created by javier apaez on 29/07/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
    func presentCharts(response: Home.Charts.Response)
    func presentNewBakcgroundColor(response: Home.BackgroundColor.Response)
    func presentSelfie(response: Home.RetriveSelfie.Response)
    func presentUploadSelfie(response: Home.UploadSelfie.Response)
}

class HomePresenter: HomePresentationLogic {
    weak var viewController: HomeDisplayLogic?
    
    // MARK: Parse and calc respnse from HomeInteractor and send simple view model to HomeViewController to be displayed
    
    func presentCharts(response: Home.Charts.Response) {
        let viewModel = Home.Charts.ViewModel()
        viewController?.displayCharts(viewModel: viewModel)
    }
    
    func presentNewBakcgroundColor(response: Home.BackgroundColor.Response) {
        let viewModel = Home.BackgroundColor.ViewModel(hexColor: response.hexColor)
        viewController?.displayNewBackgroundColor(viewModel: viewModel)
    }
    
    func presentSelfie(response: Home.RetriveSelfie.Response) {
        let viewModel = Home.RetriveSelfie.ViewModel(selfieImage: response.selfieImage)
        viewController?.displayRetriveSelfie(viewModel: viewModel)
    }
    
    func presentUploadSelfie(response: Home.UploadSelfie.Response) {
        let viewModel = Home.UploadSelfie.ViewModel()
        viewController?.displayUploadSelfie(viewModel: viewModel)
    }
}
