//
//  ChartsPresenter.swift
//  TestiOS
//
//  Created by javier apaez on 30/07/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChartsPresentationLogic {
    func PresentCharts(response: Charts.ChartsData.Response)
}

class ChartsPresenter: ChartsPresentationLogic {
    weak var viewController: ChartsDisplayLogic?

    // MARK: Parse and calc respnse from ChartsInteractor and send simple view model to ChartsViewController to be displayed

    func PresentCharts(response: Charts.ChartsData.Response) {
        let viewModel = Charts.ChartsData.ViewModel(charts: response.charts)
        viewController?.displayCharts(viewModel: viewModel)
    }
}
