//
//  ChartsWorker.swift
//  TestiOS
//
//  Created by javier apaez on 30/07/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ChartsWorker {
    func fetchChartsData(completionHandler: @escaping(Graficas) -> Void) {
        NetworkManager.shared.getCharts { result in
            switch result {
            case .success(let graficas):
                completionHandler(graficas)
            case .failure(_):
                print("error")
            }
        }
    }
}
