//
//  ChartsModels.swift
//  TestiOS
//
//  Created by javier apaez on 30/07/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Charts
{
    // MARK: Use cases
    
    enum ChartsData
    {
        struct Request
        {
            
        }
        
        struct Response
        {
            let charts: Graficas
        }
        
        struct ViewModel
        {
            let charts: Graficas
        }
    }
}
