//
//  ChartsInteractor.swift
//  TestiOS
//
//  Created by javier apaez on 30/07/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChartsBusinessLogic {
    func fetchChartsData(request: Charts.ChartsData.Request)
}

protocol ChartsDataStore {
    //var name: String { get set }
}

class ChartsInteractor: ChartsBusinessLogic, ChartsDataStore {
    var presenter: ChartsPresentationLogic?
    var worker: ChartsWorker?

    // MARK: Do something (and send response to ChartsPresenter)

    func fetchChartsData(request: Charts.ChartsData.Request) {
        worker = ChartsWorker()
        worker?.fetchChartsData(completionHandler: { [weak self] graficas in
            let response = Charts.ChartsData.Response(charts: graficas)
            self!.presenter?.PresentCharts(response: response)
        })
    }
}
